### ISSUE TITLE
setting up Workgroups

### ISSUE THREAD

**Issue by blackcrack** [snappysnappydog/Simple-IP-Config#73]
Hi,

long time is ago.. hey, nice to see you there on github !! :)))))

and hey, can you add a Setting up the Workgroup  ?

and by the way, i have W764bit on run, there works not really well ..
but reactos is comming ! :)

but the best and further like this, keep it up :) :+1: 

best regards
Blacky

**Comment by blackcrack** [comment]
jing.. and bring to top... could anyone help to add a code to setting up the workgroup ?
best

**Comment by blackcrack** [comment]
ping...

**Comment by KurtisLiggett** [comment]
I probably will not be implementing this, but anyone else is welcome to go for it.
Doesn't Windows need a restart after changing the Workgroup?
